name: Check Generated Files

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Check for changed files
        run: |
          if [ ! -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "::warning::$(git status --untracked-files=no --porcelain)"
            git diff
            echo "::error title=Changed files::There are changed files in the repository after build"
            exit 1
          fi
